export { default as App } from './App/App.js'
export { default as HomePage } from './Home-Page/home-page'
export { default as MapPage } from './mapPage/map'
export { default as BlogPage } from './blogPage/blog'
export { default as ProfilePage } from './profilePage/profile'
export { default as LoginPage } from './loginPage/login'
export { default as RegisterPage } from './registerPage/register'